import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";
test.use({ channel: "chrome" });
const url = process.env.AIRPOINTER_E2E_URL || "http://localhost:3000";

test("installation-free case finds a frame, reviews evidence, and exports a passive report", async ({ page }) => {
  test.setTimeout(90_000);
  const localRequests: string[] = [];
  const errors: string[] = [];
  page.on("request", r => { if (/\/api\/(agent|companion)/.test(r.url())) localRequests.push(r.url()); });
  page.on("pageerror", e => errors.push(e.message));
  let calls = 0;
  let transmittedEvidence = "";
  let alertAt = 0;
  await page.route("**/api/analyze", async route => {
    calls++;
    const body = route.request().postDataJSON();
    if (calls === 1) return route.fulfill({ status: 503, json: { error: "일시적인 분석 오류 · 다시 시도해 주세요." } });
    if (body.exploration.round === 0) return route.fulfill({ json: { explorationRequests: [{ type: "frames", offsetsSeconds: [-(body.metadata.capturedAt - alertAt - 100) / 1000] }] } });
    transmittedEvidence = body.frames.at(-1);
    return route.fulfill({ json: { analysis: "일시적인 결제 오류가 표시됐습니다.", evidence: [{ frameIndex: body.frames.length - 1, claim: "오류 메시지가 나타났습니다." }], incident: { title: "결제 재시도 실패", facts: ["결제 오류가 표시됨"], possibleCause: "화면만으로 내부 원인은 확인할 수 없습니다.", nextChecks: ["주문 처리 상태를 확인하세요."] }, captureContext: "최근 60초 · 샘플 화면" } });
  });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(url);
  await page.getByRole("button", { name: "30초 체험하기" }).click();
  await expect(page.getByRole("button", { name: "결제 요청", exact: true })).toBeVisible();
  const before = await page.locator("canvas[aria-label]").evaluate((canvas: HTMLCanvasElement) => canvas.toDataURL());
  await page.getByRole("button", { name: "주문 10429 이준호 선택" }).click();
  await page.getByRole("button", { name: "수량 늘리기" }).click();
  await page.getByRole("button", { name: "간편결제", exact: true }).click();
  await expect(page.getByText("2개 · 178,000원", { exact: true })).toBeVisible();
  const after = await page.locator("canvas[aria-label]").evaluate((canvas: HTMLCanvasElement) => canvas.toDataURL());
  expect(after).not.toBe(before);
  expect(calls).toBe(0);
  await page.screenshot({ path: "test-results/competition-entry.png", fullPage: true });
  await page.getByRole("button", { name: "결제 요청", exact: true }).click();
  await expect(page.getByText("알림 도착", { exact: true })).toBeVisible();
  alertAt = await page.evaluate(() => Date.now());
  const analyze = page.getByRole("button", { name: "방금 알림 찾아줘" });
  await expect(analyze).toBeEnabled();
  await analyze.click();
  await expect(page.locator("#how").getByText("일시적인 분석 오류 · 다시 시도해 주세요.")).toBeVisible({ timeout: 60_000 });
  await page.getByRole("button", { name: "같은 기록으로 다시 분석" }).click();
  await expect(page.getByRole("heading", { name: "결제 재시도 실패" })).toBeVisible({ timeout: 30_000 });
  const cinema = page.getByLabel("시간 되감기 뷰어");
  await expect(cinema).toHaveAttribute("data-phase", "revealed", { timeout: 10_000 });
  await expect(page.getByText(/DETAIL ×/)).toBeVisible();
  await page.getByRole("button", { name: "근거 발견 장면 다시 보기" }).click();
  await expect(cinema).toHaveAttribute("data-phase", "rewinding");
  await page.getByRole("slider", { name: "리플레이 시간 직접 탐색" }).focus();
  await page.keyboard.press("ArrowLeft");
  await expect(cinema).toHaveAttribute("data-phase", "manual");
  await page.waitForTimeout(3000);
  await expect(cinema).toHaveAttribute("data-phase", "manual");
  await page.getByRole("button", { name: /이 순간으로 되감기/ }).click();
  await expect(cinema).toHaveAttribute("data-phase", "revealed", { timeout: 10_000 });
  await page.getByRole("button", { name: "전후 원본 보기" }).click();
  await expect(page.getByAltText("선택한 과거 화면")).toBeVisible();
  await page.getByRole("dialog", { name: "근거 타임머신" }).getByRole("button", { name: /닫기/ }).click();
  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "보고서 다운로드" }).click();
  const download = await downloadPromise;
  const html = await readFile((await download.path())!, "utf8");
  expect(html).toContain("결제 재시도 실패");
  expect(html).toContain("data:image/");
  expect(html).toContain(transmittedEvidence);
  expect(html).toContain("샘플 시나리오");
  expect(html).not.toContain("<script");
  await page.getByRole("checkbox", { name: "1번째 근거 보고서에 포함" }).uncheck();
  await page.getByRole("button", { name: "질문 수정", exact: true }).click();
  await page.getByRole("button", { name: "AI로 사라진 오류 찾기" }).click();
  await expect(page.getByRole("heading", { name: "결제 재시도 실패" })).toBeVisible({ timeout: 30_000 });
  await expect(page.getByRole("checkbox", { name: "1번째 근거 보고서에 포함" })).toBeChecked();
  await expect(cinema).toHaveAttribute("data-phase", "revealed", { timeout: 10_000 });
  await page.screenshot({ path: "test-results/competition-result.png", fullPage: true });
  expect(localRequests).toEqual([]);
  expect(errors).toEqual([]);
  for (const width of [768, 390]) {
    await page.setViewportSize({ width, height: 844 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: `test-results/competition-${width}.png`, fullPage: true });
  }
});
